hosts:
  baseDirectory: ~/.hosts
  output: /var/tmp/etc_hosts

external:
  - url: https://github.com/uBlockOrigin/uAssets/raw/master/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt
    output: 99-blocks.host
    transform:
      - search: 127.0.0.1
        replace: 0.0.0.0
      - search: ^$
      - search: ^#.*?$
      - search: ^.*?(local|localhost|broadcasthost|ip6).*?$
      - search: ^\s+#.*?$
