hosts:
  baseDirectory: ~/.hosts
  output: /var/tmp/etc_hosts

external:
  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/thirdparties/hosts-file.net/ad_servers.txt
  output: 99-blocks.host
  mappings:
    - search: 127.0.0.1
      replace: 0.0.0.0
  skip:
    - ^0\.0\.0\.0\s.*?\s+.*?$
    - ^$
    - ^#.*?$
    - ^.*?(local|localhost|broadcasthost|ip6).*?$
    - ^\s+#.*?$