hosts:
  baseDirectory: ~/.hosts
  output: /var/tmp/etc_hosts

blacklist:
  url: https://someonewhocares.org/hosts/hosts
  output: 99-someone-who-cares
  mappings:
    - search: 127.0.0.1
      replace: 0.0.0.0
  skip:
    - 0\.0\.0\.0\s.*?\s+.*?$